"""Runtime resource containers exported by SAP Warp.

Source note: the SAP modifications in this package are based on Newton's
collision/runtime resource code and adapted for compatibility with
Newton-owned Warp arrays.
"""

from .collision_model import SapCollisionModel, SapCollisionState, sap_collision_model_from_model, sap_collision_state_from_state
from .mesh import SapMesh
from .sdf import (
    SAP_SDF_BACKGROUND_VALUE,
    SapSDF,
    SapSDFData,
    sap_check_tile_occupied_mesh_kernel,
    sap_check_tile_occupied_primitive_kernel,
    sap_compute_mesh_signed_volume,
    sap_compute_mesh_signed_volume_kernel,
    sap_compute_sdf_from_shape,
    sap_create_empty_sdf_data,
    sap_get_distance_to_mesh,
    sap_int_to_vec3f,
    sap_sample_sdf_extrapolated,
    sap_sample_sdf_grad_extrapolated,
    sap_sdf_from_mesh_kernel,
    sap_sdf_from_primitive_kernel,
)
from .sdf_kernels import (
    SAP_AXIS_X,
    SAP_AXIS_Y,
    SAP_AXIS_Z,
    sap_get_primitive_extents,
    sap_sdf_box,
    sap_sdf_box_grad,
    sap_sdf_capsule,
    sap_sdf_capsule_grad,
    sap_sdf_cone,
    sap_sdf_cone_grad,
    sap_sdf_cylinder,
    sap_sdf_cylinder_grad,
    sap_sdf_ellipsoid,
    sap_sdf_ellipsoid_grad,
    sap_sdf_plane,
    sap_sdf_plane_grad,
    sap_sdf_sphere,
    sap_sdf_sphere_grad,
)
from .texture_sdf import (
    SapTextureSDFQuantizationMode,
    sap_block_coords_from_subgrid_required,
    sap_build_coarse_sdf_from_mesh_kernel,
    sap_build_sparse_sdf_from_mesh,
    sap_check_subgrid_linearity_kernel,
    sap_check_subgrid_occupied_kernel,
    sap_create_sparse_sdf_textures,
    sap_create_texture_sdf_from_mesh,
    sap_create_texture_sdf_from_volume,
    sap_populate_subgrid_texture_float32_kernel,
    sap_populate_subgrid_texture_uint16_kernel,
    sap_populate_subgrid_texture_uint8_kernel,
    sap_sample_volume_at_positions_kernel,
    sap_texture_id_to_xyz,
    sap_texture_idx3d,
)

__all__ = [
    "SAP_AXIS_X",
    "SAP_AXIS_Y",
    "SAP_AXIS_Z",
    "SAP_SDF_BACKGROUND_VALUE",
    "SapCollisionModel",
    "SapCollisionState",
    "SapMesh",
    "SapSDF",
    "SapSDFData",
    "SapTextureSDFQuantizationMode",
    "sap_block_coords_from_subgrid_required",
    "sap_build_coarse_sdf_from_mesh_kernel",
    "sap_build_sparse_sdf_from_mesh",
    "sap_check_tile_occupied_mesh_kernel",
    "sap_check_tile_occupied_primitive_kernel",
    "sap_check_subgrid_linearity_kernel",
    "sap_check_subgrid_occupied_kernel",
    "sap_compute_mesh_signed_volume",
    "sap_compute_mesh_signed_volume_kernel",
    "sap_compute_sdf_from_shape",
    "sap_create_sparse_sdf_textures",
    "sap_create_texture_sdf_from_mesh",
    "sap_create_texture_sdf_from_volume",
    "sap_get_primitive_extents",
    "sap_collision_model_from_model",
    "sap_collision_state_from_state",
    "sap_create_empty_sdf_data",
    "sap_get_distance_to_mesh",
    "sap_int_to_vec3f",
    "sap_populate_subgrid_texture_float32_kernel",
    "sap_populate_subgrid_texture_uint16_kernel",
    "sap_populate_subgrid_texture_uint8_kernel",
    "sap_sample_volume_at_positions_kernel",
    "sap_sample_sdf_extrapolated",
    "sap_sample_sdf_grad_extrapolated",
    "sap_sdf_from_mesh_kernel",
    "sap_sdf_from_primitive_kernel",
    "sap_sdf_box",
    "sap_sdf_box_grad",
    "sap_sdf_capsule",
    "sap_sdf_capsule_grad",
    "sap_sdf_cone",
    "sap_sdf_cone_grad",
    "sap_sdf_cylinder",
    "sap_sdf_cylinder_grad",
    "sap_sdf_ellipsoid",
    "sap_sdf_ellipsoid_grad",
    "sap_sdf_plane",
    "sap_sdf_plane_grad",
    "sap_sdf_sphere",
    "sap_sdf_sphere_grad",
    "sap_texture_id_to_xyz",
    "sap_texture_idx3d",
]
